# Generated by Django 4.2.7 on 2024-04-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaLink', '0006_alter_review_blog_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_blog',
            old_name='user_id',
            new_name='username',
        ),
    ]
